import discord
from discord.ext import commands
import os
import random

class Fun(commands.Cog): # create a class for our cog that inherits from commands.Cog
    # this class is used to create a cog, which is a module that can be added to the bot

    def __init__(self, bot): # this is a special method that is called when the cog is loaded
        self.bot = bot

    @discord.slash_command(name="8ball", description="Frage den heiligen 8ball und erhalte heilige Antworten!")
    async def eightball(
            self,
            ctx,
            question: discord.Option(discord.SlashCommandOptionType.string, description="Deine Frage an den 8ball")
        ):
        responses = [
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Ja',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Nein',
            'Vielleicht',
            'Vielleicht',
            'Vielleicht',
            'Vielleicht',
            'Vielleicht',
            'Vielleicht',
            'Vielleicht',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Könnte man durchaus in Betrach ziehen',
            'Durchaus möglich...',
            'Durchaus möglich...',
            'Durchaus möglich...',
            'Durchaus möglich...',
            'Durchaus möglich...',
            'Durchaus möglich...',
            'Meine Quellen sagen Nein, sie sagen aber auch dass Trump ist ein guter Präsident ist',
            'Meine Quellen sagen Nein, sie sagen aber auch dass Trump ist ein guter Präsident ist',
            'Meine Quellen sagen Nein, sie sagen aber auch dass Trump ist ein guter Präsident ist',
            'Meine Quellen sagen Nein, sie sagen aber auch dass Trump ist ein guter Präsident ist',
            'Meine Quellen sagen Nein, sie sagen aber auch dass Trump ist ein guter Präsident ist',
            'Meine Quellen sagen Nein, sie sagen aber auch dass Trump ist ein guter Präsident ist',
            'Meine Quellen sagen Nein, sie sagen aber auch dass Trump ist ein guter Präsident ist',
            'Meine Quellen sagen Nein, sie sagen aber auch dass Trump ist ein guter Präsident ist',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Definitiv.',
            'Konzentriere dich und frage nochmal',
            'Konzentriere dich und frage nochmal',
            'Konzentriere dich und frage nochmal',
            'Konzentriere dich und frage nochmal',
            'Konzentriere dich und frage nochmal',
            'Konzentriere dich und frage nochmal',
            'Konzentriere dich und frage nochmal',
            'Konzentriere dich und frage nochmal',
            'Konzentriere dich und frage nochmal',
            'Ohne einen Zweifel.',
            'Ohne einen Zweifel.',
            'Ohne einen Zweifel.',
            'Ohne einen Zweifel.',
            'Ohne einen Zweifel.',
            'Ohne einen Zweifel.',
            'Ohne einen Zweifel.',
            'Ohne einen Zweifel.',
            'Ohne einen Zweifel.',
            'Ohne einen Zweifel.',
            'Ohne einen Zweifel.',
            'Ohne einen Zweifel.',
            'OH GOTT NEIN',
            'OH GOTT NEIN',
            'OH GOTT NEIN',
            'OH GOTT NEIN',
            'OH GOTT NEIN',
            'OH GOTT NEIN',
            'Oh god please have mercy with me',
            'Oh god please have mercy with me',
            'Oh god please have mercy with me',
            'Oh god please have mercy with me',
            'Oh god please have mercy with me',
            'Oh god please have mercy with me',
            'Das sag ich dir lieber nicht...',
            'Das sag ich dir lieber nicht...',
            'Das sag ich dir lieber nicht...',
            'Das sag ich dir lieber nicht...',
            'Das sag ich dir lieber nicht...',
            'Das sag ich dir lieber nicht...',
            'Das unterliegt einer Schweigepflicht',
            'Das unterliegt einer Schweigepflicht',
            'Das unterliegt einer Schweigepflicht',
            'Das unterliegt einer Schweigepflicht',
            'Das unterliegt einer Schweigepflicht',
            'Das unterliegt einer Schweigepflicht',
            'Als Strafe für diese Frage musst du alle 900 Krogs sammeln und darfst dann erst wieder atmen',
            'Versuchs morgen wieder',
            'Möglicherweise',
            'Ja, aber mache es hardcore betrunken :beers:',
            'Tu was Jesus gemacht hat, sterb mit einem Alter von 33',
            'Zweifelhaft',
            'Auf jeden Fall',
            'HELL YESSS, GIRLLLL. GO FOR IT',
            'Wenn du den morgigen Tag noch erleben möchtest, TU ES NICHT',
            'Ohne Zweifel',
            'Keine Ahnung',
            'Du musst schon hart verzweifelt sein wenn du einer KUGEL solch eine Frage stellt, hm?',
            'Frag später nicht nochmal nach',
            'Frag doch einfach nochmaaaaal',
            'Halts Maul, du Nutte',
            'Es ist Montag, lass mich inruhe',
            ':zzz:',
            'Kommst du nicht selber drauf??',
            'Wie kommst du auf die Idee das ein Stück Plastik die Antwort weiß??',
            'Hau ab.',
            'Geh weg. Bitte.',
            'Ich schlafe mit deiner Frau',
            'Bitte. Geh sterben.',
            'Och nee, die haben jetzt nicht noch Trump mit reingezogen... oder??',
            'BITTTCCHH, natürlich ist die Antwort nein',
            'Bitte verlasse diesen Server.',
            'Frag doch einfach deine Mülltonne. Die weiß wie man dein Müll kompensiert',
            'Hier. Hast. Du. Scheiße. :poop:',
            ':poop:',
            'Ich liebe dich auch... nicht.',
            '/ban',
            'Nachdem du gestern mit meiner Freundin fremdgegangen bist, ist meine Antwort das hier: :knife:',
            'Was? Ich verstehe kein Idiotisch',
            'Frag lieber ob es wieder Lucky Blocks geben wird.',
            'Du wirst niemals Glücklich werden nach dieser Frage...',
            'Hat deine Mutter dich als Kind auf dem Kopf fallen lassen?',
            'B Ö L Ü M',
            'B Ö L Ü M',
            'B Ö L Ü M',
            'B Ö L Ü M',
            'B Ö L Ü M',
            'B Ö L Ü M',
            'B Ö L Ü M',
            'Nein aber Lutz ist doof.',
            'War deine Schaukel als Kind gegen die Wand gerichtet?',
            'Ich sehe deine Zukunft... Und sehe Schwarz',
            'Well, duh',
            'Wie oft hat deine Mutter dich als Kind runterfallen lassen? Frage aus interesse...',
            'Zu einer Wahrscheinlichkeit von 99,999%',
            'Die Antwort liegt in deinem Magen... Vergammelt, zerkaut und ohne Sinn.',
            'Ich wusste nicht dass ich als KUGEL solche Aggressionen verspüren kann...',
            'Bitte... Hör einfach auf...',
            'Darf ich dir Geld geben und du hörst auf mich jemals wieder anzusprechen?'
        ]
        random.shuffle(responses)
        embed = discord.Embed(title="8Ball", 
                              description=f"Frage: {question}\nAntwort: {random.choice(responses)}", 
                              color=discord.Color.blue(),
                              thumbnail="https://cdn.pixabay.com/photo/2015/09/05/07/17/pool-ball-923833_960_720.png",
                            )
        embed.set_footer(text=f"Frage gestellt von {ctx.author.display_name}")
        await ctx.respond(embed=embed)

def setup(bot): # this is called by Pycord to setup the cog
    bot.add_cog(Fun(bot)) # add the cog to the bot