name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker buildx build -t ${{ secrets.DOCKER_IMAGE_NAME }} .

    - name: Save Docker Image as Tar
      run: docker save -o image.tar ${{ secrets.DOCKER_IMAGE_NAME }}

    - name: Set permissions
      run: chmod 755 ./image.tar
    - name: Check file existence
      run: ls -l ./image.tar
    - name: Copy Docker Image to SSH Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: image.tar
        target: /home/tomshuffle-bot/
    - name: Load Docker Image on SSH Server and Run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker load -i /home/tomshuffle-bot/image.tar
          docker stop ${{ secrets.DOCKER_IMAGE_NAME }} || true
          docker rm ${{ secrets.DOCKER_IMAGE_NAME }} || true
          docker run -d -p 8000:8000 --name ${{ secrets.DOCKER_IMAGE_NAME }} -e TOKEN=${{secrets.DISCORD_BOT_TOKEN}} -v /home/tomshuffle-bot/db:/db ${{ secrets.DOCKER_IMAGE_NAME }}